### ISSUE TITLE
uMatrix blocks 255.255.255.255 -> NoScript blocks every Script, even tho it is marked at 

### ISSUE THREAD

**Issue by xiriloj-installlinux** [hackademix/noscript#121]
Hi, I use the Brave Browser Nightly with uBlock + uMatrix + Noscript
Yesterday I noticed, that uMatrix blocks 255.255.255.255 I looked in the Network Traffic and saw that NoScript wanted to send this:

![image](https://user-images.githubusercontent.com/56113470/70376574-61d5f280-190a-11ea-8fe9-d98dd22431b6.png)

If uMatrix blocks this, NoScript blocks scripts, even tho they are displayed as Trusted in the gui.
If I allow that XHR request, NoScript allows Scripts from trusted sources.

Why does NoScript send this? 
https://github.com/hackademix/noscript/blob/master/src/lib/SyncMessage.js

My System:
```
Brave	1.4.9 Chromium: 79.0.3945.70 (Official Build) nightly (64-bit)
Revision	65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS	Linux
JavaScript	V8 7.9.317.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.70 Safari/537.36
Command Line	/opt/brave.com/brave-nightly/brave --disable-domain-reliability --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,WebXR,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,WebXrGamepadModule,AllowPopupsDuringPageUnload,SyncUSSBookmarks --disable-webrtc-apm-in-audio-service --enable-dom-distiller --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --enable-oop-rasterization=Enabled --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --password-store=basic --sync-url=https://no-thanks.invalid --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,PasswordImport --disable-features=SyncUSSBookmarks,AllowPopupsDuringPageUnload,WebXrGamepadModule,UnifiedConsent,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,WebXR,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/opt/brave.com/brave-nightly/brave
Profile Path	~/.config/BraveSoftware/Brave-Browser-Nightly/Default
```

**Comment by hackademix** [comment]
NoScript doesn't actually "send" anything. It initiates a fake HTTP request (https://255.255.255.255 wouldn't go anywhere anyway, as the broadcast address has no meaning in a HTTP request context) and intercepts it with its own webRequest listener, redirecting it to a data: URL in order to provide the content script with synchronous configuration data: something which would be otherwise impossible without this hack given the current WebExtensions API.
In other words, this is an internal communication channel for NoScript, and no network traffic is generated.
BTW, you've been able to see it in uBlock by a chance, probably just because uBlock has been installed earlier than NoScript and therefore its webRequest listener are called earlier than NoScript's. Otherwise the fake request would have been swallowed by NoScript and couldn't reach uBlock.
Regarding the reason why NoScript blocks all the scripts if this XHR fails, that's simple: in absence of policy data for a certain page, which may be due to any kind of browser or extensions bug (NoScript couldn't tell for sure), NoScript defaults to the most restrictive policy as a security measure.
