### ISSUE TITLE
when an https domain is marked UNTRUSTED the http version remains DEFAULT

### ISSUE THREAD

**Issue by bughit** [hackademix/noscript#126]
- fx 71.0, ns 11.0.10
- new profile
- load https://example.org/
- mark it UNTRUSTED
- load http://example.org/
- it's still DEFAULT

when a domain is declared untrusted, loading it over http certainly doesn't make it any less untrusted, so by default untrusted should be added without the secure §: prefix and because this is a privilege escalation I think it makes sense to migrate existing §:untrusteds.

**Comment by hackademix** [comment]
That's actually a bug, because the desirable behavior you're describing was also the intended one, but unfortunately [a "siteKey = " assignment was missing](https://github.com/hackademix/noscript/blob/b58225d4789b8eed23f8d4b88a126bd50776fc6e/src/common/Policy.js#L430) :(

Fixed by eaf3c8376e6a05bd20919e0f08c356982bc6abf8, thank you.
