### ISSUE TITLE
Cannot play videos when media is blocked in Firefox for Android (81)

### ISSUE THREAD

**Issue by acatarineu** [hackademix/noscript#157]
It seems the click-to-play prompt is not displayed in Android (perhaps it's not implemented there yet?). We are currently seeing this in Tor Browser nightlies (based on Fenix).

**Comment by hackademix** [comment]
On Firefox for Android, where the browser.windows API is not available, you were supposed to enable media using the menu.
However this should have been fixed with commit a50a8298b3c962446ccfcfa8be27b4d045ca3efb - which could actually use some more beta testing - already avaialble in recent RCs ( https://noscript.net/getit#devel ) and probably tomorrow in the release channel.

**Comment by acatarineu** [comment]
This seems to be working indeed thanks!

I have to say that the text is a bit too small, though:

![noscript_small](https://user-images.githubusercontent.com/16651385/95504535-2b935480-09ad-11eb-949b-df46e7ece897.png)

It's a bit difficult to read and interact with it. But maybe this can be addressed in a different issue and this one be closed.
