### ISSUE TITLE
Req: XPI-file: Non-cryptic name

### ISSUE THREAD

**Issue by Jonta** [hackademix/noscript#158]
Right now, going to `~/.mozilla/firefox/[profile-ID]/extensions/`, this extension is identified by an opaque hex-string

An example of an extension that has a clear name, is HTTPS Everywhere: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

=)

**Comment by hackademix** [comment]
That's because NoScript is 15 years old, (v 1.0 dating back to 2005), long before anything except GUIDS was allowed as an extension ID. HTTPS Everywhere is much more recent (actually it started by reusing the code from the "force HTTPS" feature of NoScript classic), therefore it could afford a less opaque ID.
Changing NoScript's IDs along the way would break automatic updates (because from Firefox's standpoint it would be a brand new extension), which is something an extension with millions of users just can't afford.
