### ISSUE TITLE
Please don't use CSS variables with name as simple as --icon-size to avoid breaking pages.

### ISSUE THREAD

**Issue by SuperPat45** [hackademix/noscript#232]
Since the latest version, the file
https://github.com/hackademix/noscript/blob/main/src/common/themes.css , who is injected in all web pages, use new CSS variables like:
```
:root {
  --icon-size: 2em;
  --line-size: 1.5em;
  --popup-size: 600px;
}
```

This break my web application because I, unfortunately, use the same name:
--icon-size
and your file has priority over my own CSS.

I think all CSS variables should be prefixed by --noscript to avoid breaking pages.

**Comment by hackademix** [comment]
You're right, that's been an accidental mistake due to the hurry of putting out the Vintage Blue theme switch. 

The rule selectors were not meant to be the naked :root and .vintage, but the more specific and unlikely to create collisions .__NoScript_Theme__ and .__NoScript_Theme___.vintage.

Fixing this in the next iteration, thanks for noticing.
