### ISSUE TITLE
[Bug] OpenSpeedTest doesn't work, even with restrictions disabled

### ISSUE THREAD

**Issue by Tech-How** [hackademix/noscript#366]
Hi there,
Today I've come across an issue where the website [openspeedtest.com](https://openspeedtest.com) will not work with NoScript. However, even after fully disabling all NoScript restrictions, the website still does not work. It will only work after disabling the NoScript extension from Firefox manually. Is this something that can be looked into?

**Comment by hackademix** [comment]
Thank you very much for your report.

The bug seems due to the site using SVG documents as "applets", and the synchronous fetching of security policy from within those causing an unexpected delay and breaking the main HTML document's assumption they're already intialized.

I'm fixing this over the weekend, the patch will be in next dev build and next stable.

**Comment by hackademix** [comment]
Should be fixed in [latest dev build](https://noscript.net/getit/#development-build).
Please verify, thank you.

**Comment by Tech-How** [comment]
Working great now, thank you!
