### ISSUE TITLE
Cloudflare protections break MV3 NoScript, which fallbacks to block everything.

### ISSUE THREAD

**Issue by hackademix** [hackademix/noscript#393]
From #390:

> Had to disable the extension in order to pass the captcha on [Nexus Mods' login page](https://users.nexusmods.com/auth/sign_in), disabling restrictions for the tab did not do anything.
> At least, that seems to be the case....

Found the culprit in the `Permissions-Policy` header set by Cloudflare-protected pages breaking syncrhonous XHR and therefore NoScript Commons Library's `SyncMessage` API.

Fixing that in 12.0.4.

**Comment by hackademix** [comment]
Please check [NoScript 12.0.4](https://noscript.net/getit/#nonstore-versions-for-chromium), waiting for approval on the Chrome Store.

**Comment by Twisted-Code** [comment]
\o/ will check it out immediately (the sooner I can stop letting scripts treat my PC like a revolving door, the better)

**Comment by Twisted-Code** [comment]
I'm having an issue with Desmos again. This time it hasn't —so far— mysteriously disappeared from switching tabs. I think Desmos relies on at least some capabilities provided by cloudflare (for instance, when I first started investigating this issue on my end, I noticed formulas on their help pages would break about a minute after the page loaded, and I would see cloudflare mentioned at the bottom of the page), so it might still be related.
Of course it's also possible I didn't update the dev mode plug-in correctly. Let me just start from scratch to be sure.

Minor update:
... Okay fresh install didn't help, but at least this time "disable restrictions for this tab" worked, so that's at least an improvement. (and of course disabling the extension entirely works but that leaves the revolving door unlocked and set to max speed). It might just be a new capability that I'm not permitting?
Minor update:
Setting all to temp trusted seems to work also, so I guess I just need to figure out which capability. The extension might be working as intended and it was just poor timing with the Desmos issue.

**Comment by Twisted-Code** [comment]
Okay, the ball is back in your court, and I am very confused 🤷. The website does not work right after loading my settings from 12.0.2, but works as soon as I change away from custom profile and then back it works?
Immediately after loading (website does not work):
![image](https://github.com/user-attachments/assets/1be282c7-82c1-45f2-88cf-375db83c2732)
Switch to temp trusted (website starts working):
![image](https://github.com/user-attachments/assets/95dfc648-0901-43bd-b0c9-fd366a528a16)
Switch back to the exact same settings I had before in custom profile (Website continues working):
![image](https://github.com/user-attachments/assets/a402c716-734c-4a4e-82cf-7caba0c7cbfe)
Is something going wrong when loading the data from the store extension's context? Is what I'm seeing here even relevant to the cloudflare issue? I don't know, but hopefully you do.

**Comment by Twisted-Code** [comment]
The same weirdness (aside from where it starts working at step 2; my default is implicit deny and it is as painful as it sounds) occurs if I switch to the default profile instead of temp trusted and then back to custom...

**Comment by hackademix** [comment]
This one is fixed in 12.0.4. Opened #394 for the follow up contextual policies bug.
