### ISSUE TITLE
Option to hide the shortened addresses when “list full addresses in the permissions popup” is checked

### ISSUE THREAD

**Issue by jcfyre** [hackademix/noscript#395]
Currently on Firefox mobile (specifically Android) when I check “list full addresses in the permissions popup” it will show both the shortened and expanded addresses, but it would be nice to be able to only show the expanded addresses when that option is active for less clutter with more details.

**Comment by jtotht** [comment]
I like the ability to choose on a case-by-case basis whether I want to configure the top-level domain or the specific subdomain, so I hope the option to show both remains; but I’m not against *also* having an option to show only full addresses (i.e. turn the binary option into a ternary one).

**Comment by jcfyre** [comment]
It's nice to see the full address but when it shows both  “...google.com” form and “https://www.google.com/” form, for every other address it gets cluttered. I am new and probably don't fully understand everything, but it would be nice to be able to just show the full addresses to each "https://..." without duplicates.

**Comment by jtotht** [comment]
They’re not duplicates (unless I’m mistaken): `….google.com` configures all *.google.com domains – www.google.com, images.google.com, maps.google.com, accounts.google.com, analytics.google.com, and so on –; `https://www.google.com`, on the other hand, only configures www.google.com.

**Comment by hackademix** [comment]
> They’re not duplicates (unless I’m mistaken): `….google.com` configures all *.google.com domains – [www.google.com](http://www.google.com), images.google.com, maps.google.com, accounts.google.com, analytics.google.com, and so on –; `https://www.google.com`, on the other hand, only configures [www.google.com](http://www.google.com).

That's correct (it configures also google.com - the 2nd level domain), i.e. is a convenience shortcut for most users.

I've created the `ux` label and started using it with this bug, as my NoScript roadmap _after stabilizing NoScript 12.x on MV3_is going to include a 3rd party usability/accessibility auditing and some UX enhancements like this.

One idea could be adding a little widget to cycle the label's granularity from `...domain.com` (default) to `sub.domain.com` to `https://sub.domain.com` (maybe graying out the segment which won't be considered at the moment, rather than hiding it).

**Comment by jcfyre** [comment]
Ah! Thank you to all for explaining that. You are a wonderful community. You developers make our world!
