### ISSUE TITLE
An obscure bug in NoScript is causing a bug in OnionShare

### ISSUE THREAD

**Issue by micahflee** [hackademix/noscript#64]
While I preparing the release of OnionShare 2, we ran into an issue that we tracked down to NoScript. Here's the issue in OnionShare: https://github.com/micahflee/onionshare/issues/899

There is a new feature called "receive mode" where a user starts a local web server, makes it a Tor onion service, and then others can use Tor Browser to load that website and upload files to the user's computer by making an HTTP POST request. For some reason, when you upload large files (>54mb), the upload nearly completes, but then hangs forever when it's on its last ~30 bytes.

After much debugging, we tracked this issue down to NoScript, which is built-in to Tor Browser. If we load Tor Browser and disable the NoScript add-on, this bug no longer happens. And in fact, we narrowed it down to a part of NoScript. If we go to NoScript's advanced settings and uncheck "Sanitize cross-site suspicious requests", the upload works fine.

The HTML page that includes the upload form doesn't have any javascript or third party resources at all, and the URL of the page doesn't include `<`, `'`, or `"` characters -- it's just `/word1-word2/upload` where word1 and word2 are random english words from a wordlist.

To reproduce:

- Open OnionShare 2 -- you can use a binary from the [2.0.dev3 release](https://github.com/micahflee/onionshare/releases/tag/v2.0.dev3) or run it from the `develop` branch following [these instructions](https://github.com/micahflee/onionshare/blob/develop/BUILD.md)

- Switch to "Receive Files" tab, and click "Start Receive Mode", in a few seconds you'll get an OnionShare URL, like `http://obpezmkec2rxmlktx2prutadzcafcnxh75vx5n5angcu66e226qkecid.onion/pennant-strangle`

- Open the latest Tor Browser (8.0.5 is what I'm using) and load the onion address

- Try uploading a large file. I've been testing with `atom-amd64.deb` from https://atom-installer.github.com/v1.34.0/atom-amd64.deb, which is 85mb. It will get to 99% and then it just stalls forever (technically, it uploads everything except for the last 15-30 kb). Tor Browser looks like it's still uploading, and OnionShare looks like it's still downloading, but it never finishes the final bytes.

- Now, open NoScript advanced settings and uncheck "Sanitize cross-site suspicious requests", and then try uploading the same large file again. It will work to upload to 100% each time.

I've tried writing a simple proof-of-concept web app to just reproduce this bug here https://github.com/micahflee/noscript-upload-bug -- and it does in fact reproduce it some of the time, but not reliably. I've found that OnionShare receive mode reproduces it reliably though.

Do you have any idea what within NoScript could be causing this bug? Right now, this is the only issue that's blocking the OnionShare 2 release. Thank you so much!

**Comment by hackademix** [comment]
Looking into this, thanks for reporting.

**Comment by hackademix** [comment]
It seems this is not a NoScript-specific issue, but a bug in the webRequest.onBeforeRequest implementation happening when the "requestBody" option is enabled (I've tested with a minimal extension which just registers an empty listener).
I'm further investigating to issue a meaningful report at https://bugzilla.mozilla.org (it might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1506562 ), but in the meanwhile I'd suggest to switch to an Ajax-based upload, since it would bypass the XSS filter listener which is filtered by "main_frame", "sub_frame" and "object".

**Comment by micahflee** [comment]
Just FYI, it looks like SecureDrop has been affected by this same issue https://github.com/freedomofpress/securedrop/issues/4078

**Comment by eloquence** [comment]
Hi @hackademix,

Thanks for the quick investigation. As @micahflee mentioned, this does impact SecureDrop, meaning that 65+ media organizations can’t receive files above ~70 MB reliably with this option enabled. That could impact the investigation of major news stories around the world. We consider this a very high priority issue.

I understand that from your perspective, this is purely an upstream bug; thanks for suggesting a workaround. For SecureDrop, we instruct sources to disable JavaScript by turning the Tor Browser Security Slider to high. This is done to to protect sources. As such, AJAX based file upload is not an option for us. 

Can you think of another workaround we could apply? Alternatively, would it make sense to limit or modify this feature within NoScript — or the version of NoScript distributed with Tor — until the browser issue is confirmed fixed? 

I understand there are security tradeoffs involved, but if SecureDrop is impacted (which uses a fairly simple web upload form), other services people are trying to use via Tor are likely impacted as well. Moreover, failures of this kind cannot easily understood by the users or developers. (We spent a lot of time investigating this issue before Micah’s report pointed us to the root cause.)

Curious what your thoughts are, and thanks for all your work on NoScript!

**Comment by hackademix** [comment]
> For SecureDrop, we instruct sources to disable JavaScript by turning the Tor Browser Security Slider to high. This is done to to protect sources. As such, AJAX based file upload is not an option for us.
> Can you think of another workaround we could apply? 
Can't you also instruct them to set their SecureDrop instance's site to TRUSTED (or Temp. TRUSTED) and therefore be able to use AJAX uploads?

> Alternatively, would it make sense to limit or modify this feature within NoScript — or the version of NoScript distributed with Tor — until the browser issue is confirmed fixed?

Unfortunately that's impossible because the way webRequest listeners are registered doesn't allow static exceptions (even conceded it would have helped your case, which I doubt), and dynamic exceptions are not an option because the bug happens even with an empty listener :(

**Comment by micahflee** [comment]
@hackademix I'd like to keep track of this upstream WebExtension bug. Did you open a new issue on Mozilla's bug tracker for it, or did you confirm that it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1506562 ? And thanks for your help in this. I don't think I would have figured it out on my own.

**Comment by eloquence** [comment]
> did you confirm that it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1506562 ?

@hackademix We're also curious about this. For now we are planning to tell users to turn off this setting to ensure they can reliably upload files to SecureDrop instances (see https://github.com/freedomofpress/securedrop/pull/4153). It would be good to know which upstream issue to track to achieve resolution. :)

**Comment by eloquence** [comment]
Cross-linking here as well, I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1532530 for now for additional follow-up.

**Comment by hackademix** [comment]
> Cross-linking here as well, I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1532530 for now for additional follow-up.

Thank you so much for filing it, and sorry for not having been able to do it myself earlier: unfortunately I cannot currently log-in on bugzilla.mozilla.org with my 15 years old account, seemingly disabled because a weird DNS misconfiguration on their side, so it's very welcome from you.
I'll CC myself on your bug report as soon as I can log in again (waiting for the administrators to sort this out), or maybe you can try to already CC :mao:, if a disabled account can be added to the list anyway.

**Comment by eloquence** [comment]
I was able to add you, but it may be an old email address (begins with `i` and ends with `n.com`).
