### ISSUE TITLE
Bug: NoScript 10.2.1 + Firefox 65.0.2 leads to huge memory leak/usage

### ISSUE THREAD

**Issue by danowar2k** [hackademix/noscript#67]
I just deactivated NoScript on a Firefox 65.0.2 installation because of this possible bug.

System:
Windows 7 SP1 64Bit
RAM: 8GB
Firefox 65.0.2
NoScript 10.2.1

What I could reproduce was:
- Have ca. 8 tabs open (two of them were Youtube videos)
- Close Firefox
- Reopen Firefox
- Click on a tab to make the page load
- Watch the Windows 7 task manager create a firefox.exe process that quickly consumes up to 6-7 GB RAM
- Watch the PC stop in its tracks because the system is constantly swapping like mad

I'd like to generate some debug log or something, but you'd have to help me as I'm not familiar with those in Firefox.
Also, it will probably a pain to generate because of the whole swapping/not reacting bit.

So, what can I do?

**Comment by hackademix** [comment]
Thank you for your report. At this moment I've got 108 tabs open (10 of them pinned) and I always use the session restore functionality, which seems to be your scenario, with no problem whatsoever, so it's definitely configuration (or site) specific.
Could you please take note of the specific URLs of each of the tabs and disable all the other extensions you've got in order to exclude potential conflict. Or, even better, try on a clean profile with just NoScript installed (you can manage browser profiles from about:profiles)?
Thanks!

**Comment by hackademix** [comment]
Thank you for your report. At this moment I've got 108 tabs open (10 of them pinned) and I always use the session restore functionality, which seems to be your scenario, with no problem whatsoever, so it's definitely configuration (or site) specific.
Could you please take note of the specific URLs of each of the tabs and disable all the other extensions you've got in order to exclude potential conflict. Or, even better, try on a clean profile with just NoScript installed (you can manage browser profiles from about:profiles)?
Thanks!

**Comment by danowar2k** [comment]
Didn't happen anymore and I switched to Chrome, so...
