### ISSUE TITLE
Reset button doesn't reset the Appearance|List full addresses in the permissions popup (https://www.noscript.net)

### ISSUE THREAD

**Issue by businessBoris** [hackademix/noscript#69]
Just installed add-on for the first time and playing about .. and so resetting a lot.
Just noticed that the third option down on the Appearance tab doesn't reset when the Reset button is pushed.

Obviously no biggie,. but perhaps something else is surviving reset too?

I really like it so far; excellent job.

Meta: Version 10.2.5

**Comment by hackademix** [comment]
Thank you. It was quite a subtler bug: once you used the [Reset] button, the defaults for "secondary" options (not the main policy) like those in the Appearance tab become a live reference to current settings, therefore resetting them didn't work anymore until the browser or the extension was restarted.
Fixed in commit 9493978.
