### ISSUE TITLE
Wrong domain shown

### ISSUE THREAD

**Issue by bjorn3** [hackademix/noscript#90]
`https://logincdn.msauth.net/16.000.28230.1/ConvergedLoginPaginatedStrings.nl.js` is shown as being hosted on ...**28230.1**.

![noscript_bug](https://user-images.githubusercontent.com/17426603/60684013-a103a180-9e9b-11e9-85a4-43cdda2aa3ad.png)

**Comment by hackademix** [comment]
Nope.
The line you're referring to (the first with a failed CORS request in the console) is correctly reported as ..msauth.net.
The CORS error line below, whose URL starts with with https://lgincdnvzeuno.azureedge.net16.000.28230.1/, has at least one typo (a missing slash) causing the domain to be parsed until 28230.1 (correctly). The bug is in the site, not in NoScript.

**Comment by bjorn3** [comment]
I see :)

**Comment by eliotcole-projectfive** [comment]
This has been in my head for months! Thanks, Giorgio!
