### ISSUE TITLE
Allow syncing whitelists across devices using the same profile

### ISSUE THREAD

**Issue by mitchcurtis** [hackademix/noscript#91]
I started using NoScript yesterday, and just realised now that the whitelists aren't synced across my devices, meaning that I need to repeat the same whitelistings on three different devices, even if I'm "signed in" to Firefox on each device.

I'm aware that it's possible to manually export the whitelists, and I will probably end up doing that, but having an option to sync the whitelists automatically would make this so much less painful.

**Comment by da2x** [comment]
This is just a matter of replacing `browser.storage.local` with `browser.storage.sync` and doing a one-time migration on upgrade from one to the other.

**Comment by mitchcurtis** [comment]
Could that be made an option in the preferences?

I also noticed this when searching for "sync" - something to be aware of perhaps:

https://github.com/hackademix/noscript/issues/1

**Comment by mitchcurtis** [comment]
@da2x where is that change supposed to be done?

**Comment by mitchcurtis** [comment]
@hackademix sorry to bother you about this, but importing and exporting the whitelist manually across devices is getting really old. Is there a way to do this that I'm missing?

**Comment by Rik44444** [comment]
yes please build in sync for whitelists!! I use firefox on 4 different devices and keep adding rules :p I'm not an IT expert so I don't understand the comment by da2x

**Comment by issu-shooter** [comment]
seriously syncing can ease the pain of exporting a lot!

**Comment by snhv** [comment]
Another vote for syncing!

**Comment by irdroid3** [comment]
It looks like the `browser.storage.sync` that @da2x referred to, is something the developer needs to change. 
Should the whole options set be synced or just the whitelist? - I vote for the easiest, and sync the whole set.

**Comment by irdroid3** [comment]
PS - I have not looked, but I assume `browser.storage.sync` is a Chrome browser option? as I see people talking about sync available in Firefox.

**Comment by hackademix** [comment]
It mostly depend of what you mean by "devices".
NoScript has been using storage.sync for storing permissions for years.
Unfortunately this API is not implemented (yet?) on Firefox for Android, where it would be most useful:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by mitchcurtis** [comment]
> It mostly depend of what you mean by "devices".

In this case I'm referring to laptops and PCs (though I do use FireFox on Android too, but I don't bother trying to use NoScript there).

> NoScript has been using storage.sync for storing permissions for years.

Does this mean that it is possible to have permissions synced automatically? If so, how do we go about doing this?

**Comment by hackademix** [comment]
> Does this mean that it is possible to have permissions synced automatically? If so, how do we go about doing this?

Yes, you've got it by default (as long a "Extensions" are among the item set to  be synced by Firefox sync).
But there's a **BIG caveat:** if your NoScript settings' [total size exceed ~100KB](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#Storage_quotas_for_sync_data) (not uncommon, I guess), sync storage won't work and NoScript falls back to local storage (and no synchronization).
This limit could actually be much lower (~8KB), since per-site permissions are a JSON struct treated by the browser as a single "item", but NoScript uses some [chunking tricks](https://github.com/hackademix/noscript/blob/master/src/common/Storage.js) to work around this. Unfortunately there's nothing to do about the 100KB overall limit, other than maybe adding some JSON-compatible non-binary compression scheme to the (already messy) mix.
Frankly, too much work. Maybe in the future I could try to implement some kind of custom synchronization for permissions, using browser.storage.sync only to share a UUID and a symmetric encryption key across devices for end-to-end encryption, and providing a synchronization server of my own as a premium service.
